### ISSUE TITLE
Refresh EzVarSequence and visibility

### ISSUE THREAD

**Issue by ylemontag** [adufour/EzPlug#10]
Hi,

Here is my problem: I create a EzPlug plugin with a EzVarSequence input whose visibility depends on the value of another EzVar (through the addVisibilityTriggerTo method). If I open a sequence when the EzVarSequence is hidden, this sequence will not be present in the list when the EzVarSequence will become visible.

Thanks.

**Comment by DrDaleks** [comment]
That one got fix somewhere in the past...
