### ISSUE TITLE
Possible Memory Leak in EzVarSequence

### ISSUE THREAD

**Issue by 53RT** [adufour/EzPlug#15]
Dear adufour,

considering the following usage scenario i think there is a memory leak in the EzVarSequence dropdown component.

1. Open a plugin that uses the ezVarSequence 
2. load a sequence into icy (the sequence will be listed in the ezVarSequence)
3. close and reopen the plugin (the sequence will be shown in the new instance of the plugin)
4. close the sequence (the sequence disappears from the ezVarSequence list)

after those steps the sequence remains in memory even though it is not selectable in the dropdown list

Would be great if you have a fix for this

**Comment by adufour** [comment]
Nice one. Turns out it's even simpler: open an image/sequence _before_ an EzPlug, then close the image/sequence. Still there.
duh!
Should be fixed as of 3.15.1 (just committed).
Thx!

**Comment by 53RT** [comment]
works perfect.
Thanks
